using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using NUnit.Framework;

namespace AdventOfCode2020
{
    [TestFixture(TestName = "Day 20: Jurassic Jigsaw")]
    public sealed class Day20
    {
        [Test, Ignore("Slow")]
        public void Part1()
        {
            Assert.AreEqual(7492183537913, ProductOfCorners(Day20Input));
        }

        [Test, Ignore("Slow")]
        public void Part1Sample()
        {
            Assert.AreEqual(20899048083289, ProductOfCorners(Day20SampleInput));
        }

        [Test, Ignore("Slow")]
        public void Part2()
        {
            Assert.AreEqual(2323, WaterRoughness(Day20Input));
        }

        [Test, Ignore("Slow")]
        public void Part2Sample()
        {
            Assert.AreEqual(273, WaterRoughness(Day20SampleInput));
        }

        private static long ProductOfCorners(string[] input) =>
            RelativeTiles(input)
                .Where(kvp => kvp.Value.Count == 2)
                .Aggregate(1L, (product, current) => product * current.Key.Id);

        private static long WaterRoughness(string[] input)
        {
            var relativeTiles = RelativeTiles(input);

            var image = CreateImage(relativeTiles);
            Debug.WriteLine(string.Join(Environment.NewLine, image));

            const long seaMonsterSize = 15;
            var imageTile = new Tile(-1, image);
            var seaMonsters = imageTile.Orientations.Max(i => CountSeaMonsters(i.Content));
            var hashes = CountHashes(image);

            return hashes - seaMonsters * seaMonsterSize;
        }

        private static string[] CreateImage(IDictionary<Tile, HashSet<Tile>> relativeTiles)
        {
            var corners = relativeTiles.Where(kvp => kvp.Value.Count == 2).Select(kvp => kvp.Key).ToList();
            var sides = relativeTiles.Where(kvp => kvp.Value.Count == 3).Select(kvp => kvp.Key).ToList();
            var middles = relativeTiles.Where(kvp => kvp.Value.Count == 4).Select(kvp => kvp.Key).ToList();

            var sideLength = (long) Math.Sqrt(relativeTiles.Count);

            var tiles = new Tile[sideLength, sideLength];

            for (var row = 0; row < sideLength; row++)
            for (var column = 0; column < sideLength; column++)
            {
                if (row == 0)
                {
                    if (column == 0)
                    {
                        // top-left
                        tiles[row, column] = corners[0];
                        corners.Remove(corners[0]);
                    }
                    else if (column == sideLength - 1)
                    {
                        // top-right
                        var corner = corners.First(t => relativeTiles[t].Contains(tiles[row, column - 1]));
                        tiles[row, column] = corner;
                        corners.Remove(corner);
                    }
                    else
                    {
                        // top edge
                        var edge = sides.First(t => relativeTiles[t].Contains(tiles[row, column - 1]));
                        tiles[row, column] = edge;
                        sides.Remove(edge);
                    }
                }
                else if (row == sideLength - 1)
                {
                    if (column == 0)
                    {
                        // bottom-left
                        var corner = corners.First(t => relativeTiles[t].Contains(tiles[row - 1, column]));
                        tiles[row, column] = corner;
                        corners.Remove(corner);
                    }
                    else if (column == sideLength - 1)
                    {
                        // bottom-right
                        var corner = corners.First(t => relativeTiles[t].Contains(tiles[row - 1, column]));
                        tiles[row, column] = corner;
                        corners.Remove(corner);
                    }
                    else
                    {
                        // bottom edge
                        var edge = sides.First(t => relativeTiles[t].Contains(tiles[row, column - 1]) && relativeTiles[t].Contains(tiles[row - 1, column]));
                        tiles[row, column] = edge;
                        sides.Remove(edge);
                    }
                }
                else if (column == 0)
                {
                    // left edge
                    var edge = sides.First(t => relativeTiles[t].Contains(tiles[row - 1, column]));
                    tiles[row, column] = edge;
                    sides.Remove(edge);
                }
                else if (column == sideLength - 1)
                {
                    // right edge
                    var edge = sides.First(t => relativeTiles[t].Contains(tiles[row, column - 1]) && relativeTiles[t].Contains(tiles[row - 1, column]));
                    tiles[row, column] = edge;
                    sides.Remove(edge);
                }
                else
                {
                    // middle
                    var middle = middles.First(t => relativeTiles[t].Contains(tiles[row, column - 1]) && relativeTiles[t].Contains(tiles[row - 1, column]));
                    tiles[row, column] = middle;
                    middles.Remove(middle);
                }
            }

            for (var row = 0; row < sideLength - 1; row++)
            for (var column = 0; column < sideLength - 1; column++)
            {
                var tile = tiles[row, column];
                var tileRight = tiles[row, column + 1];
                var tileDown = tiles[row + 1, column];
                var oriented = tile.Orientations.Single(o => tileRight.Orientations.Any(o.MatchesRight) && tileDown.Orientations.Any(o.MatchesBottom));
                tiles[row, column] = oriented;
            }

            for (var column = 0; column < sideLength - 1; column++)
            {
                var row = sideLength - 1;
                var tile = tiles[row, column];
                var tileRight = tiles[row, column + 1];
                var tileUp = tiles[row - 1, column];
                var oriented = tile.Orientations.Single(o => tileRight.Orientations.Any(o.MatchesRight) && tileUp.Orientations.Any(o.MatchesTop));
                tiles[row, column] = oriented;
            }

            for (var row = 0; row < sideLength - 1; row++)
            {
                var column = sideLength - 1;
                var tile = tiles[row, column];
                var tileLeft = tiles[row, column - 1];
                var tileDown = tiles[row + 1, column];
                var oriented = tile.Orientations.Single(o => tileLeft.Orientations.Any(o.MatchesLeft) && tileDown.Orientations.Any(o.MatchesBottom));
                tiles[row, column] = oriented;
            }

            {
                var row = sideLength - 1;
                var column = sideLength - 1;
                var tile = tiles[row, column];
                var tileLeft = tiles[row, column - 1];
                var tileUp = tiles[row - 1, column];
                var oriented = tile.Orientations.Single(o => tileLeft.Orientations.Any(o.MatchesLeft) && tileUp.Orientations.Any(o.MatchesTop));
                tiles[row, column] = oriented;
            }

            for (var row = 0; row < sideLength; row++)
            for (var column = 0; column < sideLength; column++)
            {
                tiles[row, column] = tiles[row, column].WithoutBorder();
            }

            var tileSize = tiles[0, 0].Content.Length;
            List<string> wholeImage = new();
            for (var row = 0; row < sideLength; row++)
            for (var tileRow = 0; tileRow < tileSize; tileRow++)
            {
                var sb = new StringBuilder();
                for (var column = 0; column < sideLength; column++)
                {
                    var tile = tiles[row, column];
                    sb.Append(tile.Content[tileRow]);
                }

                wholeImage.Add(sb.ToString());
            }

            return wholeImage.ToArray();
        }

        private static readonly Regex SeaMonster1 = new(@"^..................#.", RegexOptions.Compiled);
        private static readonly Regex SeaMonster2 = new(@"^#....##....##....###", RegexOptions.Compiled);
        private static readonly Regex SeaMonster3 = new(@"^.#..#..#..#..#..#...", RegexOptions.Compiled);

        private static long CountSeaMonsters(string[] image)
        {
            var seaMonsters = 0L;
            for (var row = 0; row < image.Length - 2; row++)
            for (var column = 0; column < image[row].Length - 19; column++)
            {
                if (SeaMonster1.IsMatch(image[row][column..]) &&
                    SeaMonster2.IsMatch(image[row + 1][column..]) &&
                    SeaMonster3.IsMatch(image[row + 2][column..]))
                {
                    seaMonsters++;
                }
            }

            return seaMonsters;
        }

        private static long CountHashes(string[] image) =>
            image.Sum(row => row.Count(c => c == '#'));

        private static Dictionary<Tile, HashSet<Tile>> RelativeTiles(string[] input)
        {
            var tiles = SplitOnBlank(input).Select(Tile.Create).ToArray();

            return tiles.ToDictionary(
                t => t,
                t => tiles.Where(o => t != o && t.IsNeighbour(o)).ToHashSet()
            );
        }

        private sealed record Tile(long Id, string[] Content)
        {
            private static readonly Regex IdFormat = new(@"^Tile (?<id>\d+):$", RegexOptions.Compiled);

            public static Tile Create(string[] input)
            {
                var id = long.Parse(IdFormat.Match(input[0]).Groups["id"].Value);
                return new Tile(id, input.Skip(1).ToArray());
            }

            public Tile WithoutBorder()
            {
                var contentWithoutBorder = Content.Skip(1).Take(Content.Length - 2).Select(row => row[1..^1]).ToArray();
                return this with {Content = contentWithoutBorder};
            }

            public IEnumerable<Tile> Orientations
            {
                get
                {
                    yield return this;
                    yield return Rotate90Clockwise();
                    yield return Rotate90Clockwise().Rotate90Clockwise();
                    yield return Rotate90Clockwise().Rotate90Clockwise().Rotate90Clockwise();
                    yield return FlipVertically();
                    yield return FlipVertically().Rotate90Clockwise();
                    yield return FlipVertically().Rotate90Clockwise().Rotate90Clockwise();
                    yield return FlipVertically().Rotate90Clockwise().Rotate90Clockwise().Rotate90Clockwise();
                }
            }

            public bool IsNeighbour(Tile tile) => Orientations.Any(o => tile.Orientations.Any(o.MatchesBottom));

            private Tile FlipVertically()
            {
                var flippedContent = Content.Reverse().ToArray();
                return this with {Content = flippedContent};
            }

            private Tile Rotate90Clockwise()
            {
                var rotatedContent = Enumerable.Range(0, Content.Length)
                    .Select(row => new string(Enumerable.Range(0, Content[0].Length).Select(column => Content[column][Content.Length - 1 - row]).ToArray()))
                    .ToArray();
                return this with {Content = rotatedContent};
            }

            public bool MatchesLeft(Tile tile) =>
                Content.Select(row => row[0]).SequenceEqual(tile.Content.Select(row => row[^1]));

            public bool MatchesRight(Tile tile) => tile.MatchesLeft(this);

            public bool MatchesTop(Tile tile) => Content[0] == tile.Content[^1];

            public bool MatchesBottom(Tile tile) => tile.MatchesTop(this);
        }

        private static IEnumerable<string[]> SplitOnBlank(IEnumerable<string> input)
        {
            List<string> current = new();
            foreach (var line in input)
            {
                if (line == string.Empty)
                {
                    yield return current.ToArray();
                    current = new();
                }
                else
                {
                    current.Add(line);
                }
            }

            if (current.Any())
            {
                yield return current.ToArray();
            }
        }

        private static readonly string[] Day20SampleInput =
        {
            "Tile 2311:",
            "..##.#..#.",
            "##..#.....",
            "#...##..#.",
            "####.#...#",
            "##.##.###.",
            "##...#.###",
            ".#.#.#..##",
            "..#....#..",
            "###...#.#.",
            "..###..###",
            "",
            "Tile 1951:",
            "#.##...##.",
            "#.####...#",
            ".....#..##",
            "#...######",
            ".##.#....#",
            ".###.#####",
            "###.##.##.",
            ".###....#.",
            "..#.#..#.#",
            "#...##.#..",
            "",
            "Tile 1171:",
            "####...##.",
            "#..##.#..#",
            "##.#..#.#.",
            ".###.####.",
            "..###.####",
            ".##....##.",
            ".#...####.",
            "#.##.####.",
            "####..#...",
            ".....##...",
            "",
            "Tile 1427:",
            "###.##.#..",
            ".#..#.##..",
            ".#.##.#..#",
            "#.#.#.##.#",
            "....#...##",
            "...##..##.",
            "...#.#####",
            ".#.####.#.",
            "..#..###.#",
            "..##.#..#.",
            "",
            "Tile 1489:",
            "##.#.#....",
            "..##...#..",
            ".##..##...",
            "..#...#...",
            "#####...#.",
            "#..#.#.#.#",
            "...#.#.#..",
            "##.#...##.",
            "..##.##.##",
            "###.##.#..",
            "",
            "Tile 2473:",
            "#....####.",
            "#..#.##...",
            "#.##..#...",
            "######.#.#",
            ".#...#.#.#",
            ".#########",
            ".###.#..#.",
            "########.#",
            "##...##.#.",
            "..###.#.#.",
            "",
            "Tile 2971:",
            "..#.#....#",
            "#...###...",
            "#.#.###...",
            "##.##..#..",
            ".#####..##",
            ".#..####.#",
            "#..#.#..#.",
            "..####.###",
            "..#.#.###.",
            "...#.#.#.#",
            "",
            "Tile 2729:",
            "...#.#.#.#",
            "####.#....",
            "..#.#.....",
            "....#..#.#",
            ".##..##.#.",
            ".#.####...",
            "####.#.#..",
            "##.####...",
            "##..#.##..",
            "#.##...##.",
            "",
            "Tile 3079:",
            "#.#.#####.",
            ".#..######",
            "..#.......",
            "######....",
            "####.#..#.",
            ".#...#.##.",
            "#.#####.##",
            "..#.###...",
            "..#.......",
            "..#.###..."
        };

        private static readonly string[] Day20Input =
        {
            "Tile 3457:",
            "##.###.##.",
            "...#..##.#",
            "#.#..###..",
            "##.....#..",
            "#.#....#.#",
            "...##.#...",
            "##..#....#",
            "..###..#..",
            "#........#",
            "#.##..#.#.",
            "",
            "Tile 3061:",
            "##....####",
            "#.#.......",
            "#.....##..",
            "#........#",
            ".....#....",
            "##......##",
            ".##..###..",
            "........#.",
            "...#....#.",
            "..###.#.##",
            "",
            "Tile 2131:",
            ".#..#..#.#",
            "#....#..##",
            "#........#",
            "#..#..#..#",
            ".#...#..#.",
            "##........",
            "##.##..###",
            "..#..##...",
            "......##.#",
            "##..######",
            "",
            "Tile 2087:",
            ".##.#.....",
            "...#......",
            "###.......",
            "#.#......#",
            "##....#.#.",
            "..........",
            "........##",
            "#.....#.#.",
            "...##.#...",
            "..##.##..#",
            "",
            "Tile 2593:",
            "#.###.##.#",
            ".#..#...#.",
            ".........#",
            "#..###....",
            "....##....",
            "##..#..#..",
            "###.##....",
            "#....####.",
            ".#..##..#.",
            ".#.....###",
            "",
            "Tile 1277:",
            "###.#.#...",
            "..##......",
            "#..#.#...#",
            "...##.#..#",
            "#...###.#.",
            "..#......#",
            "##...#....",
            "......#.##",
            "##.#.##..#",
            "..#...#...",
            "",
            "Tile 2917:",
            "###.#....#",
            "....##.###",
            "#......#.#",
            "#..#.#...#",
            "#.#....##.",
            "#..#..#.#.",
            "..#####...",
            "##.##.#.##",
            "#.#....###",
            "#####.#..#",
            "",
            "Tile 1579:",
            "#.#..#..##",
            "..#....###",
            "##......#.",
            "#...#..###",
            "#..##..#..",
            "##.##....#",
            ".##....#.#",
            "#.###...#.",
            "..#.#.#.#.",
            "##.#.#....",
            "",
            "Tile 3011:",
            "....#.#.#.",
            "##........",
            "#.#......#",
            "#...#..#.#",
            "........##",
            "#..#.....#",
            ".....#....",
            "#.##......",
            "#...#..#..",
            "....#..#..",
            "",
            "Tile 2539:",
            "..#.#.#.##",
            "...#.#####",
            ".........#",
            "..........",
            ".....##..#",
            "##....##.#",
            "#.....#...",
            "....##.#..",
            "..#.##.#..",
            "#.#.#....#",
            "",
            "Tile 1879:",
            "##.#######",
            "#..#....#.",
            "........##",
            "..#.....#.",
            "#.#.#..#..",
            "...##....#",
            "#..##..#.#",
            "..#.....#.",
            "#.....#...",
            ".#####.##.",
            "",
            "Tile 2081:",
            "..#....#.#",
            "#.##.#.#.#",
            "#....#.##.",
            "##......##",
            "....#.#.##",
            "......#..#",
            "##.......#",
            "#........#",
            "..#..#...#",
            "..###..#..",
            "",
            "Tile 1721:",
            ".#.####.##",
            "....#.#..#",
            "#...#.#...",
            "#...#.##..",
            "#.#.#.####",
            "#...#.#..#",
            ".........#",
            "..#..##.#.",
            "#.#.#.##.#",
            "#..#....#.",
            "",
            "Tile 1237:",
            ".....###..",
            ".......#..",
            "#...#....#",
            "......#.##",
            "###....#..",
            "#.#..#.#..",
            "..#......#",
            "..#..#..#.",
            ".#........",
            "#.#.#.##..",
            "",
            "Tile 3037:",
            "..#..####.",
            "........#.",
            "...#.#...#",
            ".##.##..#.",
            "#.##.#.#..",
            "#...#.#.##",
            "#..###....",
            "#......###",
            "#.#..###.#",
            ".##...#.##",
            "",
            "Tile 2719:",
            "######.##.",
            "#...#...#.",
            "#..##.#..#",
            "##........",
            "..#.##....",
            "##........",
            "#.###.###.",
            "#..#....#.",
            "##..##....",
            ".#....#.#.",
            "",
            "Tile 1013:",
            ".#...#.##.",
            "#..#.##...",
            "##..#....#",
            "#......#..",
            ".#..##....",
            "..#.......",
            "........##",
            "#........#",
            ".....##...",
            "#.#.###...",
            "",
            "Tile 3571:",
            ".......#.#",
            ".#...#...#",
            "....##....",
            "#......#.#",
            ".###.#..#.",
            "#...##...#",
            "##...#.#..",
            "......#...",
            "#.#....#..",
            "##....#..#",
            "",
            "Tile 2269:",
            "##.#.#...#",
            "..#.#.....",
            ".##.###..#",
            ".#....##.#",
            "#.#..#.###",
            "#.....#..#",
            "#.#.#....#",
            "#..##..#.#",
            "...#....##",
            "...##.#...",
            "",
            "Tile 3709:",
            "##...#..##",
            "...#...#.#",
            "#..#.#....",
            "..##.####.",
            "..#...##.#",
            "...#...#.#",
            "#...#.#...",
            ".#........",
            "..........",
            "#..#.#.#.#",
            "",
            "Tile 2143:",
            "#.##.#....",
            "####...##.",
            "#.###...#.",
            "....##.#.#",
            "##.##.....",
            ".......#.#",
            "####..##..",
            ".......#..",
            "#......#.#",
            "####....##",
            "",
            "Tile 3677:",
            "##.###.##.",
            ".#.###..#.",
            "..##...#..",
            "..#......#",
            "##.##.....",
            "#.#.##.#..",
            "..#..#.##.",
            "##..###...",
            "#.#......#",
            "...###.###",
            "",
            "Tile 2297:",
            ".........#",
            "..........",
            "........##",
            "#.#..#....",
            "##.#..###.",
            "#........#",
            ".....#..#.",
            "...#...#.#",
            "##..#.....",
            ".#.######.",
            "",
            "Tile 1871:",
            "#.#.#.....",
            "#.#....#.#",
            "..#...#..#",
            "..#..##..#",
            "#.#.##....",
            "......#.##",
            "##.##.#.##",
            "#.###.####",
            "#..#....#.",
            "###.#....#",
            "",
            "Tile 3449:",
            "##..#.###.",
            ".####.....",
            "#..###..#.",
            "#....#.#..",
            "#.....#..#",
            "#....#.#..",
            "#.....#..#",
            ".#..#.....",
            "#..#.#...#",
            ".####.####",
            "",
            "Tile 3391:",
            "........##",
            "##.#.#.#.#",
            "...##....#",
            "..###..###",
            ".#....#..#",
            ".#....#.#.",
            "..........",
            "#...#.#.#.",
            ".....#.#.#",
            "#.#.......",
            "",
            "Tile 2243:",
            "..#...##.#",
            "##...##...",
            "..#......#",
            "..#.##.#.#",
            ".#......#.",
            "#.#...##..",
            "#.....###.",
            "##..##.#.#",
            "#.#....#.#",
            "#.#..#..##",
            "",
            "Tile 2153:",
            "##.###.#.#",
            ".#.#.#.#.#",
            "#..#..###.",
            ".##..#.#.#",
            ".#.....#..",
            "..#......#",
            "........##",
            ".#.....##.",
            ".#.......#",
            "#......###",
            "",
            "Tile 3659:",
            ".#.#....##",
            "..#..#..#.",
            "..###...##",
            "..........",
            "#.....#..#",
            "##.#.#..##",
            "#.###..#..",
            "#..#....##",
            "#........#",
            "#.###..##.",
            "",
            "Tile 2503:",
            "##..##.#.#",
            "#..#..#...",
            ".....#...#",
            "...#.....#",
            "#.....#...",
            ".....###.#",
            "#..#..#...",
            "..#...#...",
            "#..#...##.",
            ".###...###",
            "",
            "Tile 2741:",
            "#..#.#####",
            "..#.......",
            "...#..##..",
            "#...#.....",
            ".#.#.#....",
            "..###..#..",
            ".#.#..#..#",
            ".##..#.##.",
            "##.#......",
            ".##....#.#",
            "",
            "Tile 3371:",
            "..###.#..#",
            "#..#......",
            "###...#..#",
            "..........",
            ".#..##...#",
            "...#.....#",
            "...##.#...",
            "#.#.#..#..",
            "#.......#.",
            "###.#.###.",
            "",
            "Tile 2731:",
            "#...#.#...",
            "#.#..#....",
            "#...#.#...",
            "#.###.####",
            ".#.##....#",
            "##..#....#",
            "#.#.......",
            "##..#....#",
            "......##..",
            "###...###.",
            "",
            "Tile 3217:",
            ".#..#..#.#",
            "##...#...#",
            "....##..#.",
            "#...#.#...",
            "#......###",
            "##.#....##",
            "#..#...##.",
            "#...#...##",
            "#.#.#.....",
            ".#.#......",
            "",
            "Tile 3911:",
            "..###..##.",
            ".....#.#..",
            "##.#...#.#",
            "#.....#..#",
            ".......#.#",
            "#........#",
            "..#....#.#",
            "#.##....##",
            ".....#...#",
            "##.##.#.#.",
            "",
            "Tile 1637:",
            ".#.#..#.##",
            "##..#.#...",
            ".#.#####.#",
            "..#..#..#.",
            "#......###",
            "#.........",
            "#.##...##.",
            "#........#",
            "#..#.....#",
            "..#...#.#.",
            "",
            "Tile 3989:",
            ".#..##.##.",
            "..........",
            "..#.##..##",
            "#.#..#....",
            "#...#....#",
            "#..#.#.#.#",
            "##....#..#",
            "#.#...#...",
            "######.##.",
            ".#..#..###",
            "",
            "Tile 2213:",
            "...#..####",
            ".....###..",
            "##....###.",
            "#...###.##",
            "##...####.",
            "#.........",
            "......#...",
            "#.......##",
            "###.....##",
            ".##...###.",
            "",
            "Tile 1061:",
            ".#.....##.",
            "#...#..#.#",
            "#.......#.",
            ".#.......#",
            ".....#....",
            ".#....#.##",
            "##.#....##",
            "#...#...#.",
            "#...#.##..",
            ".###.....#",
            "",
            "Tile 2281:",
            "..#..##.#.",
            "..##.....#",
            "..##.....#",
            "..#.#....#",
            "#.#..##.#.",
            "#..#..#.##",
            "#......#..",
            "...#...#.#",
            "..##......",
            "#.###.###.",
            "",
            "Tile 3803:",
            "####.##..#",
            "#..#..#.##",
            ".#...##...",
            "#..#.#.##.",
            "#...#....#",
            "....#....#",
            "..#.##.#..",
            "#..#...#..",
            "##........",
            "#...#.#...",
            "",
            "Tile 3347:",
            ".##.##...#",
            "#..#.#....",
            "...##.##..",
            "#...#.....",
            "#.....##..",
            "#.#..#...#",
            ".....#.#.#",
            "#.........",
            "#.........",
            "##..#####.",
            "",
            "Tile 2687:",
            ".#####.#..",
            "#.#.#.....",
            "#....#....",
            ".##.#.....",
            "#.##....##",
            "#....#...#",
            "###.##...#",
            "##..#....#",
            "....#....#",
            "#.##.#.##.",
            "",
            "Tile 1097:",
            "##....#..#",
            "....##...#",
            "#...#.#...",
            "#....#....",
            ".....#..##",
            "#..##.#..#",
            "#....#....",
            "###....###",
            "#.....#.##",
            "#....#...#",
            "",
            "Tile 1483:",
            "#..#.##...",
            "....##.#.#",
            "...##....#",
            "#..##..#.#",
            ".#...##...",
            "..........",
            "#..#..##..",
            "....##.#.#",
            "######....",
            "####....#.",
            "",
            "Tile 2207:",
            ".#.###.##.",
            ".##..#....",
            "....#....#",
            "#....#....",
            "#....##..#",
            "#.#.....##",
            "...#....#.",
            "#.#..#...#",
            ".#.......#",
            ".#####.##.",
            "",
            "Tile 1559:",
            ".####..##.",
            "##..##.#.#",
            "......##..",
            "##.#..#..#",
            ".#.#.#....",
            "#....#..#.",
            "#..#..#.#.",
            "#.#..#.#.#",
            "#...##.#..",
            ".#...#....",
            "",
            "Tile 3019:",
            "...#.###.#",
            ".##..#..##",
            "...##..#..",
            "..#...##.#",
            "#......#..",
            "#....#.###",
            "##..#....#",
            "#.#....#..",
            "#..##..#.#",
            "#.#####..#",
            "",
            "Tile 2441:",
            "...####.#.",
            "#..#.#...#",
            "...##.#..#",
            "#.#......#",
            "#..#.#.#..",
            "#..##....#",
            ".####.#...",
            ".#.#...#..",
            "..##..#..#",
            ".#..#.#...",
            "",
            "Tile 1997:",
            ".##.###...",
            "......#..#",
            "....#.#..#",
            "..#.##...#",
            ".....##..#",
            "###.#.#...",
            "##........",
            "#.....#...",
            "##....#.##",
            "######..##",
            "",
            "Tile 1481:",
            "####.#####",
            "##.#.....#",
            "#.#....#.#",
            ".......#..",
            "#........#",
            "#....##...",
            "...#..#..#",
            ".#......##",
            "....##...#",
            ".#########",
            "",
            "Tile 1811:",
            "..#..#.##.",
            ".....#.#..",
            "..#...#...",
            "##.....#..",
            ".#.#.....#",
            "...#####.#",
            "#...#.##.#",
            "....#.#..#",
            "....#.#...",
            "#..#.##...",
            "",
            "Tile 3701:",
            "####.###.#",
            "###.....##",
            "#...##.###",
            "....###.#.",
            "#.#.#..#.#",
            "..###....#",
            ".#...#...#",
            "#.##..#...",
            "####....##",
            ".#####..##",
            "",
            "Tile 1451:",
            "###.##.#..",
            "#...##.#.#",
            ".#.......#",
            "#.....#...",
            ".#........",
            "#.......##",
            "...##.#.#.",
            ".#..##..##",
            "#.#.#.....",
            "....#....#",
            "",
            "Tile 3319:",
            "....####.#",
            ".#..#...##",
            "..##.###..",
            "#...#..#.#",
            ".#........",
            "......#...",
            "........##",
            "#.....#...",
            "#.........",
            "..##.##..#",
            "",
            "Tile 2659:",
            ".##..#.#..",
            "#.#...##..",
            ".####..##.",
            ".....#####",
            "##........",
            ".#........",
            "#.#.#.....",
            ".....##...",
            "........##",
            "..#.......",
            "",
            "Tile 1433:",
            "#.##.##.##",
            ".#.....#..",
            "....#.#...",
            ".#..#.####",
            "....#.#..#",
            "####...#.#",
            ".#.#..#.#.",
            "..#......#",
            ".#.#.#.#..",
            "#.###.#.#.",
            "",
            "Tile 1409:",
            "#..###....",
            "###.......",
            "#...#..##.",
            "#.##....##",
            "..#...#..#",
            ".#..##..##",
            "..#..#...#",
            "##..#.####",
            "#....#####",
            "##..####..",
            "",
            "Tile 1747:",
            "...##.###.",
            "##...##.#.",
            "......#..#",
            "#.#.....##",
            "#..#....##",
            "###.##.#.#",
            ".......#.#",
            "#...#....#",
            "......#..#",
            "##...####.",
            "",
            "Tile 2011:",
            ".#.#..##..",
            ".......###",
            "#.#.#...##",
            "#...#.###.",
            "......###.",
            "....#.#...",
            "....#.##..",
            ".##......#",
            "##....###.",
            "###.####..",
            "",
            "Tile 1009:",
            ".#.#...###",
            "#.#.##..#.",
            "..........",
            ".....#...#",
            ".#...#..##",
            ".#..#.#.##",
            "#..####.##",
            "#.##.#.#.#",
            "..###....#",
            ".##..#....",
            "",
            "Tile 1759:",
            "#.#######.",
            "#..#....##",
            "..........",
            "..###..#.#",
            "#..###....",
            "#.######..",
            "...##.##.#",
            "#.........",
            "##.......#",
            "#...#..###",
            "",
            "Tile 1223:",
            "###..#.##.",
            "##..##....",
            "...##.....",
            "#..#.#..#.",
            "#..##.#...",
            ".#.......#",
            "...#..#.#.",
            "##.......#",
            "##........",
            ".###.#...#",
            "",
            "Tile 2467:",
            ".#.##.#.#.",
            "#.........",
            "##.....#..",
            ".##...####",
            "#..#..#..#",
            "#.#...#...",
            "........#.",
            "##.......#",
            "..#....###",
            "##....#...",
            "",
            "Tile 1571:",
            "...##.#.##",
            "..#.......",
            ".#.#..#..#",
            "..........",
            "#.......#.",
            "..#....#.#",
            "#.###.....",
            "...#..##.#",
            "..##.#..##",
            "####.....#",
            "",
            "Tile 1931:",
            "###..#.##.",
            "##.#..##..",
            "...##.##.#",
            "........#.",
            ".####...##",
            "..........",
            "#.....#..#",
            "#.....#..#",
            ".#..###..#",
            ".......##.",
            "",
            "Tile 2711:",
            "#..#.#...#",
            "#....####.",
            ".#.#..##.#",
            "#.#.#..###",
            "......##..",
            "###...##.#",
            "##..##....",
            ".....#..#.",
            "##....##.#",
            ".#...#....",
            "",
            "Tile 3331:",
            "...#.#.##.",
            ".#......#.",
            "##.#.....#",
            "#..##....#",
            ".........#",
            "##....#.#.",
            "#.#......#",
            "#.......#.",
            "##......##",
            "..##..####",
            "",
            "Tile 1979:",
            "..##.#.##.",
            "...#..###.",
            "......#.#.",
            "..#..#...#",
            "#.........",
            "#.........",
            "..#.#...#.",
            "#..#..####",
            "#...#....#",
            "##.######.",
            "",
            "Tile 1229:",
            "##.###.###",
            "#....#.#..",
            "#....##...",
            "#.....#...",
            "#.#......#",
            "##...#....",
            ".#...###.#",
            "#..#.#..##",
            "...#.#....",
            ".##...#.##",
            "",
            "Tile 1217:",
            "#..#.#....",
            ".#....#..#",
            ".#.....###",
            "..#.#....#",
            "##....#...",
            ".#...##.##",
            ".#..#.#.#.",
            ".##..##...",
            ".#....#..#",
            ".#.#.#.#.#",
            "",
            "Tile 2521:",
            ".....####.",
            "#.#....#..",
            "..#..#...#",
            "..#...#...",
            "......#...",
            "#.##..#..#",
            "..#..##..#",
            ".#..#....#",
            "#..##..###",
            "#.###.##.#",
            "",
            "Tile 2251:",
            "#...#..###",
            "...##.#.#.",
            "#..#..##..",
            "##........",
            "#.........",
            "......#.##",
            "##.....#..",
            "..#.#...#.",
            "###.#.....",
            ".###..#.#.",
            "",
            "Tile 1093:",
            "#####.#...",
            "###.....#.",
            "#.#.###..#",
            "....##....",
            "###.....##",
            ".#......#.",
            "#.........",
            "..#.......",
            "....#.....",
            "#.#.#.#...",
            "",
            "Tile 2293:",
            "##..#.##.#",
            "#...#....#",
            "#..##.....",
            "..#......#",
            "#....#....",
            ".......#..",
            "##.....###",
            "#....#....",
            "#...#..##.",
            "########..",
            "",
            "Tile 1279:",
            "#.###.##..",
            "..........",
            "#...#....#",
            ".....#...#",
            "#....#####",
            "#...#.#.#.",
            "#..#..#..#",
            ".......#..",
            "#.#...##.#",
            "#####..#..",
            "",
            "Tile 1213:",
            "#...##....",
            "##.#.....#",
            "#.....#...",
            "#.......#.",
            "#.........",
            "#.#.......",
            "#........#",
            "#....#....",
            ".#..#....#",
            ".##...##..",
            "",
            "Tile 3851:",
            "#.#...##.#",
            ".........#",
            "#.......#.",
            ".#.#.#..#.",
            ".##.....##",
            "...##...#.",
            "#.#...#..#",
            "#.....#..#",
            ".#.#......",
            ".#.#.##..#",
            "",
            "Tile 1531:",
            "..##..#...",
            "#....#....",
            "#...#.#..#",
            "....##..#.",
            "#..#..##..",
            ".##.###.##",
            "#..#####.#",
            "##.#.##...",
            "#.#.##..#.",
            "#..##.####",
            "",
            "Tile 1321:",
            "#.##.....#",
            "###.#.....",
            "#.........",
            ".......#.#",
            "#...##...#",
            ".....###.#",
            "..##...#..",
            "..#.#.##.#",
            "####....##",
            ".##...##.#",
            "",
            "Tile 1619:",
            ".###..####",
            "#..##....#",
            "#.....#...",
            "......#...",
            "#.......##",
            "#....#....",
            "##..#..#..",
            "....#...#.",
            ".#.....#..",
            ".#.#.##.##",
            "",
            "Tile 2803:",
            "#.#.#..#..",
            "#...#..#..",
            "#####.#.#.",
            ".##....#.#",
            "......#..#",
            "##..#.#..#",
            "..#..#..#.",
            "##......##",
            "..#.##...#",
            ".#.#....##",
            "",
            "Tile 2383:",
            ".####.#..#",
            "#..#..##..",
            "#..##.#..#",
            "..##...#.#",
            "##..#.##..",
            ".#........",
            "#.##..#...",
            "#......#..",
            "#...#....#",
            "##.##..#.#",
            "",
            "Tile 1291:",
            "...#.#..##",
            "##.#......",
            "....#.#.##",
            "#.#.#...##",
            ".#.##.#..#",
            "##.#...#..",
            "#..#......",
            "#.#..#....",
            "#..####..#",
            "##.....###",
            "",
            "Tile 1129:",
            "#.#....##.",
            "...#.#.#..",
            ".#.#.#...#",
            ".#..#....#",
            ".#.##....#",
            "........#.",
            ".##......#",
            "...#.#.#..",
            "#.....##..",
            ".###..#...",
            "",
            "Tile 2857:",
            "#.#.#.####",
            "...#.....#",
            "..#.....#.",
            "###.....#.",
            "###...##.#",
            "#..#.#...#",
            "#.##.###..",
            ".####..###",
            "#.##......",
            "..#..#.###",
            "",
            "Tile 2411:",
            "......##.#",
            "##..#....#",
            "#.....#..#",
            "#..#......",
            ".#...##..#",
            "#.....##..",
            "###.#..###",
            "#.#.#####.",
            "#...#.#..#",
            ".#.##.#.##",
            "",
            "Tile 3923:",
            "..#####..#",
            "#...#.#...",
            "#...##.#.#",
            "....#.....",
            "..........",
            "#.##....#.",
            ".........#",
            "##.......#",
            "#...#...##",
            "###..##.##",
            "",
            "Tile 3343:",
            "#..#.###.#",
            "..#...##.#",
            "..#...#...",
            "#...#.....",
            "..#.......",
            "##.#..#...",
            "...###..#.",
            "#.#.#.#..#",
            "...#..##.#",
            "#..#...##.",
            "",
            "Tile 2017:",
            ".#...###..",
            ".........#",
            ".##....##.",
            "....#...##",
            "..###.....",
            "##..##..#.",
            "#..#.##..#",
            "#.#..####.",
            "##........",
            "..#.##....",
            "",
            "Tile 3889:",
            "#.##.##..#",
            ".#....#.#.",
            ".##...##.#",
            "#..#.###..",
            "#..##.#...",
            "#...##.#..",
            ".#....#.##",
            "###.#.#..#",
            "#..#...#.#",
            ".#.#..##..",
            "",
            "Tile 1823:",
            "....##.##.",
            "#...#...#.",
            "..#......#",
            "..........",
            "....###..#",
            "####....#.",
            ".##......#",
            "...###.###",
            "##....#...",
            "#.#.##....",
            "",
            "Tile 3769:",
            ".#..#.....",
            "...#.....#",
            "#...#....#",
            "..#..##...",
            ".....#...#",
            "....#.....",
            "#...####.#",
            "#..#.##..#",
            "#..#....##",
            "#######.#.",
            "",
            "Tile 1523:",
            ".#.##....#",
            "...#...#.#",
            "#.........",
            ".....##.#.",
            "##.##..#..",
            "..#.##...#",
            "#...#..##.",
            "#....#....",
            ".#.#...#..",
            "#.#.###...",
            "",
            "Tile 2843:",
            "...#....#.",
            "......###.",
            "..##....##",
            "#.###.#..#",
            "#..##.#...",
            "#.##....#.",
            ".....##...",
            ".#.......#",
            "##.#..#..#",
            "#.##....#.",
            "",
            "Tile 2423:",
            "#.##.#####",
            "..#.#...#.",
            "#.....#.#.",
            "#..#.....#",
            "..##..#..#",
            "##....#..#",
            "#......#.#",
            "#.#..#.##.",
            "#.....#...",
            ".##.##.#..",
            "",
            "Tile 1999:",
            ".#..#.####",
            ".#.#..#...",
            "..........",
            "...#.#.#..",
            "..#....#.#",
            "##.#...#..",
            ".#..####..",
            ".....#.#.#",
            "..#..#..##",
            "##..#..#..",
            "",
            "Tile 2341:",
            "#....#.#.#",
            "##.##....#",
            "#..##.#...",
            "#..#.#....",
            "...#..#.#.",
            "##..##.###",
            "#.#.....##",
            ".......#.#",
            "##.##.....",
            "....#.####",
            "",
            "Tile 3359:",
            "#..###.##.",
            "#.........",
            ".####.###.",
            "#.##....#.",
            ".#..#.##..",
            "#.........",
            ".#.#.#....",
            "..#...#..#",
            "###......#",
            "...#......",
            "",
            "Tile 3863:",
            "..##.##.#.",
            "#.##..#.##",
            ".###......",
            ".#.......#",
            "..##......",
            "#..##..###",
            ".##..##...",
            "....#.#...",
            "#.#.#.##.#",
            "...##..##.",
            "",
            "Tile 3187:",
            "#.#.#.#...",
            "......###.",
            "#.....####",
            "..#.#...#.",
            "#....#..#.",
            "#......#..",
            "#...##..#.",
            "#........#",
            "#.##.....#",
            ".##.#...#.",
            "",
            "Tile 3119:",
            "##.....##.",
            "....#....#",
            "#..#..#..#",
            "#....##..#",
            "........#.",
            "...#.#....",
            "...##..#..",
            ".....#....",
            "#.####....",
            "...#..#.##",
            "",
            "Tile 1063:",
            ".#.#.#....",
            "##........",
            "#..#.##...",
            "#..#.....#",
            "....##...#",
            ".#......#.",
            "..##...##.",
            "#........#",
            "..........",
            ".#..#..#..",
            "",
            "Tile 1657:",
            ".##.#.#...",
            "##.....#.#",
            "....#.#.#.",
            "#....#####",
            "###......#",
            ".#....#..#",
            "#.#..#.#..",
            "#.#.##....",
            "##.#......",
            "#..##.#...",
            "",
            "Tile 3257:",
            "##.####..#",
            "#.#.#####.",
            "##.#..##..",
            ".##.#..###",
            "..#.......",
            "#...#.#..#",
            "#..#.#.#.#",
            "...#....##",
            "##.....##.",
            "...###..##",
            "",
            "Tile 1987:",
            ".#.#..###.",
            ".#.......#",
            "...#....##",
            "#...##....",
            ".......#.#",
            ".#.##.####",
            "...#...#..",
            ".##...#...",
            ".........#",
            ".#.##..#..",
            "",
            "Tile 1459:",
            "#.....####",
            "......#..#",
            "........#.",
            "##..#..#..",
            "###.##.#.#",
            "##..#...#.",
            "##..#.###.",
            ".##..###.#",
            "#..####...",
            ".#.#####..",
            "",
            "Tile 3533:",
            "#.##...#..",
            ".#.....#..",
            "#.##......",
            "..#.....##",
            "....#..#..",
            "##..#....#",
            "#....##..#",
            "..#....#..",
            "........##",
            ".####.##.#",
            "",
            "Tile 2789:",
            "..####...#",
            "#....###..",
            "#..#..##.#",
            "#.#..#....",
            "#....##...",
            "....#.....",
            "#.........",
            "#..#......",
            ".......#.#",
            "...####.#.",
            "",
            "Tile 2137:",
            "#..####.##",
            "....##...#",
            ".#.....#..",
            "#.#..#####",
            "...#..#...",
            ".#.....#.#",
            ".....#..#.",
            "##..#...##",
            "..#.#.....",
            "#..######.",
            "",
            "Tile 1181:",
            ".#####.#..",
            "..#.##...#",
            "#....#....",
            "#...#.#...",
            "##.......#",
            ".....#...#",
            "##..#...#.",
            ".##.##....",
            "#...##....",
            "..#.##....",
            "",
            "Tile 1117:",
            "#####.####",
            ".......#..",
            "##.#..#..#",
            "#....#.#..",
            "..........",
            "..#...#.#.",
            "......#...",
            "##...#...#",
            "....#...#.",
            "#.....##..",
            "",
            "Tile 3739:",
            "..####.#.#",
            "#.#.#.#...",
            "#.......##",
            ".##...#.#.",
            "#....#.#..",
            "#...#....#",
            "#.....##.#",
            ".......##.",
            "##...###.#",
            "....##..##",
            "",
            "Tile 2909:",
            ".##..###..",
            "#...#.....",
            ".....#...#",
            "..##......",
            "#.##.###..",
            "##.....#.#",
            "#..#...###",
            "....##....",
            "#......#..",
            "#.#...####",
            "",
            "Tile 1609:",
            "##.###.#..",
            "....#.#...",
            "#.#....##.",
            "#..##.#...",
            ".####..#.#",
            "..........",
            "##..#....#",
            "...#..#...",
            "#.........",
            "....#.###.",
            "",
            "Tile 1753:",
            "....#.###.",
            "##.##.....",
            "....##....",
            "#.....##..",
            "#.##..#...",
            "..........",
            "#..#.#..#.",
            "#.....#...",
            ".#........",
            ".#.#...#.#",
            "",
            "Tile 2003:",
            "#.#.####.#",
            "#.##.#...#",
            "####..#...",
            "###..##...",
            "###.......",
            "#.....#...",
            "..##......",
            "#....#..#.",
            "#.###...#.",
            ".#..#.###.",
            "",
            "Tile 1399:",
            "#.#..##..#",
            "....#.##.#",
            "#..#.....#",
            "#..#....##",
            "#...#..#..",
            "#.#.#....#",
            "......##..",
            ".##.......",
            ".####.####",
            "...#...#..",
            "",
            "Tile 1249:",
            "..#..####.",
            "#.##.....#",
            "..........",
            "..#.....##",
            "#.#..#...#",
            "#..#...###",
            ".....#.#.#",
            "..###..#.#",
            ".#...#..#.",
            ".#...##.#.",
            "",
            "Tile 1289:",
            "#########.",
            "...#......",
            ".....##.#.",
            "...#.#...#",
            "#..#..#...",
            "#....###.#",
            "....#..#..",
            ".....##..#",
            ".....#...#",
            ".#.#####.#",
            "",
            "Tile 3373:",
            "#...##..##",
            "#..#....##",
            "#..#...###",
            "#......#..",
            "..#......#",
            ".....#....",
            "#.#.......",
            ".....#.##.",
            "...#.#..##",
            "..##.##...",
            "",
            "Tile 1613:",
            "####...#..",
            "#.#.......",
            "..........",
            "#....#####",
            "#..#....##",
            "...#..#...",
            ".....#...#",
            ".#......##",
            "##....#..#",
            "....#..###",
            "",
            "Tile 2029:",
            "#..###.#.#",
            "#.#..#...#",
            "##...#....",
            ".#..#..#..",
            "...#...##.",
            "##.....##.",
            "..##...#.#",
            "...##.#..#",
            "#.........",
            ".#.####.##",
            "",
            "Tile 2203:",
            "..####.###",
            "..##....##",
            "...##.....",
            "....#..#.#",
            "..#...#.##",
            "#.#.......",
            "...###....",
            "#.....#..#",
            ".........#",
            ".###....#.",
            "",
            "Tile 1877:",
            "##.....###",
            ".....#..#.",
            "....#...#.",
            "##.#.....#",
            ".#..##...#",
            "##.#..##..",
            "..#...#...",
            "#...##....",
            "#.#.#.....",
            ".##..#....",
            "",
            "Tile 3847:",
            "...##.#...",
            ".##.....##",
            "#.#.#..##.",
            "#.##..###.",
            ".........#",
            "..#...##.#",
            "#...##..##",
            "##..#.##.#",
            "#..#.....#",
            "#.##.#..#.",
            "",
            "Tile 1499:",
            "..#.######",
            "#....##..#",
            "##...#...#",
            "...#.##.#.",
            "##...#...#",
            "....#....#",
            "##.....#.#",
            "#.....#...",
            ".#....#..#",
            "#.#.#..#..",
            "",
            "Tile 3251:",
            ".###.#.#.#",
            "##....####",
            "##..#.....",
            "#.#....#..",
            "...#..#.##",
            "...#......",
            "#.#.##....",
            "......##..",
            "......#...",
            "..#.##...#",
            "",
            "Tile 3323:",
            "...#.#....",
            "........##",
            "...#......",
            "#.......##",
            "###.##..##",
            "##.##....#",
            "...#..#...",
            "...###.###",
            "##.....#..",
            ".###.##..#",
            "",
            "Tile 3109:",
            ".#.#.#.###",
            "######.#..",
            "......#...",
            "##.#.#...#",
            ".#...#..##",
            "###...#.#.",
            "....#.....",
            "#....#..##",
            "#...#.#...",
            ".#....####",
            "",
            "Tile 1889:",
            "#..#.####.",
            "#..##.##..",
            "...#....##",
            "........##",
            "#.#..#####",
            "#.........",
            "#.#.#.....",
            "...###.#..",
            "#....#..#.",
            "..###.#...",
            "",
            "Tile 2027:",
            "#....##...",
            ".##....#..",
            "#...#...##",
            "#........#",
            "#.....##.#",
            ".#...#..##",
            "#..#...###",
            "....#.....",
            "#..#...##.",
            "##.#.#####",
            "",
            "Tile 2677:",
            "#..###.#.#",
            "##.#....#.",
            ".##.###.##",
            "#.........",
            "#........#",
            ".#.##.##.#",
            "##...##..#",
            "##......##",
            "...#......",
            "#..####...",
            "",
            "Tile 1663:",
            ".####.#.#.",
            "#...#....#",
            "###....##.",
            "#..##.#.##",
            "#.....#..#",
            ".#..##....",
            "#....#.#..",
            "##........",
            "#..#......",
            ".##.##..##",
            "",
            "Tile 3559:",
            "..###...#.",
            "##........",
            "..#..#..#.",
            "#.........",
            ".#.#..##.#",
            "##.#.....#",
            "..#.......",
            "#..##.#..#",
            "###.#....#",
            ".#..#..#..",
            "",
            "Tile 3049:",
            ".#.##...#.",
            "#.......#.",
            "#.##....#.",
            "...#...#.#",
            "..........",
            "####..#.#.",
            ".##.##...#",
            "...#..#.#.",
            "....#....#",
            "###.#.#.#.",
            "",
            "Tile 2777:",
            "..#.#..##.",
            "##..#...#.",
            ".....##...",
            "#.###...##",
            "##...#..#.",
            ".##......#",
            "....#....#",
            "##....#...",
            "##.....#..",
            "###.##...#",
            "",
            "Tile 2551:",
            "#.####.##.",
            "#.........",
            "#..##...##",
            "..#......#",
            "..........",
            "##...#..##",
            ".........#",
            "#.#......#",
            "..#.....#.",
            "...#.###.#",
            "",
            "Tile 3491:",
            "#.##...###",
            "#.#.#.#...",
            "#.....#..#",
            "#.....#...",
            "##..#..##.",
            "###......#",
            "#......#..",
            "....#.##.#",
            "#.##....##",
            "####.#.#.#",
            "",
            "Tile 3947:",
            "#.##.#.#..",
            "....#.#.##",
            "...##....#",
            "###......#",
            "##.#..##.#",
            "..#.#..#..",
            "#....#..#.",
            "#...#....#",
            "...#..#.##",
            "###.##.#..",
            "",
            "Tile 1361:",
            "..#.#.####",
            "#..#..#.##",
            ".#...#...#",
            "..........",
            "..#......#",
            "##........",
            "#.##.....#",
            ".#.......#",
            "#.#..#...#",
            "#..##...#.",
            "",
            "Tile 2851:",
            ".###.##...",
            "#.....##..",
            "....##...#",
            "........#.",
            "#.#.###..#",
            "#...#.#..#",
            "##...#..##",
            "...#..#...",
            "##.......#",
            "#####.#.##",
            "",
            "Tile 2381:",
            ".#.#######",
            ".#..#..##.",
            "...#......",
            "#......###",
            "#.#..#...#",
            "..###..#..",
            "...#.#.#..",
            "#......#..",
            "..##.....#",
            "..#.#.##..",
            "",
            "Tile 1069:",
            ".#.#...###",
            "##..#.##.#",
            "#.#..###..",
            "###...##..",
            ".#.#....#.",
            ".........#",
            "#..#...#..",
            "..#....##.",
            ".#.#....##",
            "#.....##.#"
        };
    }
}